# Setup
title:               Transvasive Security
tagline:             the human factor
url:                 https://transvasive.github.io
paginate:            3
baseurl:             ""
permalink:           pretty
notice: >
  I started Transvasive Security in 2008 and offered consulting services until taking a full time job in 2012.
  This site is an archive of my work prior to 2015; I currently blog at [information-safety.org](https://www.information-safety.org)
  and provide security consulting through my new company, [Security Differently](https://www.security-differently.com).

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate

# Optimize Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - bootstrap.sh
  - clean.sh
  - poole-LICENSE.md
  - poole-sass.patch
  - tmp
  - vendor

sass:
  sass_dir:          _sass
  style:             compressed

# Links to include in the masthead.
masthead_links:
  About:             '/about/'
  Blog:              '/'
  Archive:           '/archive/'

# Disqus settings
disqus_url:          transvasive

# Options

# Uncomment to enable mobile icons
#mobile-icons:        true

# Replace this value and uncomment to enable Google Analytics tracking
#google_analytics:    UA-177097512-1

# poole custom vars prevent builds from working properly (invokes github-metadata) - see https://github.com/jekyll/jekyll/issues/4705
# Custom vars
#version:             3.0.0
